### PR TITLE
I made a Japanese version of REDAME.

### PR DESCRIPTION
**Pull request by reindex-ot**
By the way, I'd like to do a translation of the Phh Settings for this, but I was wondering if you could include xml?

### CODE REVIEW

**Comment by xiaoleGun** [comment]
Yes, please send all the xml to my email 1592501605@qq.com or PR to https://github.com/exthmui-10-treble/treble_app

**Comment by reindex-ot** [comment]
Not found...
https://github.com/exthmui-10-treble/treble_app
If there are values, we will make them.

**Comment by xiaoleGun** [comment]
> https://github.com/exthmui-10-treble/treble_app

Sorry, it has been switched to public

**Comment by reindex-ot** [comment]
thx!

**Pull request merged**
